repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        stages:
          - "pre-push"
        entry: uv run pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true