name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install ruff
        run: uv pip install --system ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312

      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py312
        continue-on-error: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: uv run pytest tests
